[linux]
linux1 ansible_host=127.0.0.1 ansible_port=2221
linux2 ansible_host=127.0.0.1 ansible_port=2222
linux3 ansible_host=127.0.0.1 ansible_port=2223
linux4 ansible_host=127.0.0.1 ansible_port=2224

[linux:vars]
ansible_user=ansible
; ansible_password=ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.ssh/id_ed25519