# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell", "-Command"]

# Create user and set password
RUN net user ansible ansible /add ; `
    net localgroup Administrators ansible /add

# Configure WinRM
RUN winrm quickconfig -q ; `
    Set-Item -Path WSMan:\localhost\Service\Auth\Basic -Value $true ; `
    Set-Item -Path WSMan:\localhost\Service\AllowUnencrypted -Value $true ; `
    Set-Item -Path WSMan:\localhost\Service\Auth\CredSSP -Value $true ; `
    Enable-PSRemoting -Force ; `
    New-Item -Path WSMan:\localhost\Listener -Transport HTTP -Address * -Force

# Expose WinRM port
EXPOSE 5985

# Keep container running
CMD ["powershell.exe","-NoLogo","-ExecutionPolicy","Bypass","-Command","while ($true) { Start-Sleep -Seconds 3600 }"]